@startuml

title Admin Employee Creation Workflow

start
:Admin Login the system with;
:Admin email and password;
-> Navigate to Employee tab;
-> Click on create employee button;
-> Admin fill in the employees information;

if (Is email valid and required fields filled?) then (yes)
  -> Admin click on the Save Button;
  --> Save employee to database;
  :Employee successfully created;
else (no)
  :Display validation error message;
endif

stop

@enduml