@startuml

start

:Admin Login the system with Admin email and password;
:Navigate to Employee tab;
:Click on create employee button;
:Admin fill in the employee's information;

repeat
  :System will check for the email validation and required field.;
  if (Validation successful?) then (yes)
    :Admin click on the Save Button to save employee to database;
  else (no)
    :Display error message: "Email validation failed or required field cannot be empty.";
  endif
repeat while (Validation unsuccessful?)

stop

@enduml